[project]
name = "read-tokenize-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pypdf2>=3.0.1",
    "tiktoken>=0.9.0",
]

[dependency-groups]
dev = [
    "autopep8>=2.3.2",
]
